INSERT INTO "newspaperarchive"("orig_relpath",
                             "format_type",
                             "edition_date",
                             "single_page",
                             "page_number",
                             "avisid",
                             "avistitle",
                             "shadow_path",
                             "section_title",
                             "edition_title",
                             "delivery_date",
                             "side_label",
                             "fraktur")
VALUES ('Fjerritslev_Avis/tiff/1923/19230724_00028_M_003.tiff',
        'tiff',
        '1923-07-24', true, 003, 'fjerritslevavis',
        'Fjerritslev Avis', 'fjerritslevavis/1923/07/24/fjerritslevavis_0_M_1923_07_24_003.tiff',
        'M',
        0,
        '2000-01-01',
        '',
        false);
